/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.hillel.api;

import com.hillel.model.Homework;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-01-16T16:52:25.131245300+02:00[Europe/Helsinki]")
@Validated
@Tag(name = "homework", description = "Operations related to homework")
public interface HomeworkApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /homework : Get list of homework
     *
     * @return Successful response (status code 200)
     */
    @Operation(
        operationId = "homeworkGet",
        summary = "Get list of homework",
        tags = { "homework" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/homework",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> homeworkGet(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
    @Operation(
            operationId = "homeworkGet",
            summary = "Get list of homework",
            tags = { "homework" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful response")
            }
    )
    @GetMapping("/homework")
    ResponseEntity<List<Homework>> getAllHomeworks();

    @PostMapping("/homework")
    ResponseEntity<Homework> createHomework(@RequestBody Homework homework);

    @GetMapping("/homework/{id}")
    ResponseEntity<Homework> getHomeworkById(@PathVariable Long id);

    @PutMapping("/homework/{id}")
    ResponseEntity<Homework> updateHomework(@PathVariable Long id, @RequestBody Homework homework);

    @DeleteMapping("/homework/{id}")
    ResponseEntity<Void> deleteHomework(@PathVariable Long id);

}
